# Generated by Django 4.2.24 on 2025-10-08 19:53

from django.db import migrations, models
import django.db.models.deletion
import records.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dni', models.CharField(max_length=12, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('edad', models.PositiveSmallIntegerField()),
                ('region', models.CharField(max_length=100)),
                ('provincia', models.CharField(max_length=100)),
                ('distrito', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=255)),
                ('maps_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bpm', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('hemoglobina', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('spo2', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('lmp_date', models.DateField(blank=True, null=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('visit_number', models.PositiveSmallIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='records.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('CONJ', 'Conjuntiva'), ('LAB', 'Labio')], max_length=4)),
                ('index', models.PositiveSmallIntegerField(default=1)),
                ('file', models.FileField(upload_to=records.models.photo_upload_to)),
                ('original_name', models.CharField(blank=True, max_length=255)),
                ('content_type', models.CharField(blank=True, max_length=100)),
                ('size', models.PositiveIntegerField(default=0)),
                ('sha256', models.CharField(db_index=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='records.visit')),
            ],
        ),
        migrations.AddConstraint(
            model_name='visit',
            constraint=models.UniqueConstraint(fields=('patient', 'visit_number'), name='uniq_patient_visitnumber'),
        ),
        migrations.AlterUniqueTogether(
            name='photo',
            unique_together={('visit', 'type', 'index')},
        ),
    ]
