# Generated by Django 4.2.24 on 2025-10-10 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='visit_number',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
