# Generated by Django 5.2.3 on 2026-01-08 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_alter_visit_visit_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='type',
            field=models.CharField(choices=[('CONJ', 'Conjuntiva'), ('LAB', 'Labio'), ('IND', 'Índice')], max_length=4),
        ),
    ]
