# Generated by Django 5.2 on 2026-03-23

from django.db import migrations, models

import records.models


class Migration(migrations.Migration):

    dependencies = [
        ("records", "0003_alter_photo_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="photo",
            name="thumbnail",
            field=models.ImageField(blank=True, upload_to=records.models.photo_thumbnail_upload_to),
        ),
    ]